name: qrpay
description: A new Flutter project.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1


environment:
  sdk: ">=3.5.1 <4.2.0"
  flutter: 3.24.1

dependencies:
  flutter:
    sdk: flutter

  get: 4.6.6
  flutter_screenutil: ^5.9.3
  google_fonts: 6.2.1
  country_code_picker: 3.0.0
  get_storage: ^2.1.1
  logger: 2.4.0
  pin_code_fields: 8.0.1
  intl: 0.19.0
  image_picker: 1.1.2
  dotted_line: 3.2.2
  flutter_svg:
#  percent_indicator: ^4.2.3
  qr_code_scanner: ^1.0.1
  flip_card: ^0.7.0
  dotted_border: 2.1.0
  carousel_slider: ^5.0.0
  connectivity_plus: 6.1.0
  flutter_spinkit: ^5.2.1
#  awesome_snackbar_content: ^0.1.1
  smooth_page_indicator: ^1.2.0
#  country_list_pick: ^1.0.1+6
#  intl_phone_field: 3.2.0
  http: 1.2.2
  flutter_inappwebview: 6.1.5
  patterns_canvas: 0.5.0
  flutter_html:
  share_plus: 10.1.1
  local_auth: 2.3.0
  cached_network_image:
  path_provider: ^2.1.1
  uuid:
  flutter_local_notifications: 17.2.3
  iconsax: ^0.0.8
  flutter_animate: 4.5.0 
  flutter_staggered_animations: ^1.1.1
  qr_flutter: ^4.1.0
  liquid_swipe: ^3.1.0
  pusher_beams: ^1.1.1
  firebase_core: 3.6.0
#  jwt_decoder: ^2.0.1
  rename_app: ^1.6.1
  flutter_phoenix: ^1.1.1
  restart_app: ^1.2.1
  r_dotted_line_border: ^0.1.1
  shimmer: ^2.0.0
   
   
#dependency_overrides:
#  awesome_snackbar_content: 0.1.3
#  flutter_svg:

dev_dependencies:
  flutter_test:
    sdk: flutter
    
  flutter_launcher_icons:
  change_app_package_name: ^1.1.0
  flutter_lints: 3.0.1
  build_runner:
  flutter_gen_runner:
  dart_code_metrics:

flutter_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/logo/app_launcher.png"

flutter_gen:
  output: lib/custom_assets/ # Optional (default: lib/gen/)
  line_length: 80 # Optional (default: 80)

flutter:
  uses-material-design: true

  fonts:
    - family: AgencyFB-Bold
      fonts:
        - asset: fonts/AgencyFB-Bold.ttf

  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
  assets:
    - assets/card/
    - assets/clipart/
    - assets/icon/
    - assets/icon/agent.svg
    - assets/logo/
    - assets/qr/
